### ISSUE TITLE
UnityEvent based handler usage counts not working in Unity 2018.4+

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1448]
Event handlers based on `UnityEvent` (which includes the Event System) don't work in scenes serialised by Unity 2018.4 and above, as the type of the event is no longer serialised.

E.g. this is from Unity 2018.2. Unity 2018.4+ removes the `m_TypeName` field.

```yaml
callback:
  m_PersistentCalls:
    m_Calls:
    - m_Target: {fileID: 379208070}
      m_MethodName: TestUsages
      m_Mode: 0
      m_Arguments:
        m_ObjectArgument: {fileID: 0}
        m_ObjectArgumentAssemblyTypeName: UnityEngine.Object, UnityEngine
        m_IntArgument: 0
        m_FloatArgument: 0
        m_StringArgument: 
        m_BoolArgument: 0
      m_CallState: 2
  m_TypeName: UnityEngine.EventSystems.EventTrigger+TriggerEvent, UnityEngine.UI,
    Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```
