### ISSUE TITLE
[LTS 18.4] USS Bad suggestions

### ISSUE THREAD

**Issue by MeikelLP** [JetBrains/resharper-unity#1469]
Environment: **2018.4 LTS**

Valid (overwrites `padding-bottom`, `padding-top`, ...)
```css
Button {
    padding-right: 1px;
    padding-top: 1px;
    padding-left: 1px;
    padding-bottom: 1px;
}
```

Invalid (doesn't overwrite `padding-bottom`, `padding-top`, ...)
```css
Button {
   padding: 1px
}
```

Obviously like in CSS you would shorthand the first block to `padding: 1px`. Sadly this does not work. Rider is still suggesting this.

This is fixed in newer versions (at least 19.3) but LTS still has a relevant user base.
